2.9 release day
mozilla/mozillavpn-product-details pull request #40
Opened 2022-07-25 14:25 UTC by strseb

2022-07-25 14:26 UTC, strseb commented on docs/mozillavpn.json
>      "IOS": "2.8.2",
iOS is certainly not going out today, so we need to update this later :)

2022-07-25 16:54 UTC, bakulf requested changes

2022-07-25 16:54 UTC, bakulf commented on docs/mozillavpn.json
> +      "platforms": ["ANDROID", "IOS", "LINUX", "MACOS", "WINDOWS"]
not IOS

2022-07-26 17:08 UTC, strseb commented on docs/mozillavpn.json
> +      "platforms": ["ANDROID", "IOS", "LINUX", "MACOS", "WINDOWS"]
removed :)

2022-07-28 16:03 UTC, bakulf approved these changes

2022-07-28 16:16 UTC, merged