release 2.12.0 version updates
mozilla/mozillavpn-product-details pull request #51
Opened 2022-12-06 22:36 UTC by mozrokafor

release 2.12.0 version updates

2022-12-07 00:29 UTC, birdsarah requested changes
At this stage of the release process you should be updated the staging info not production.

2022-12-15 16:58 UTC, bakulf requested changes

2022-12-15 16:58 UTC, bakulf commented on docs/mozillavpn_stage.json
> +    "IOS": "2.12.0",
iOS is still 2.11 until the review is completed

2022-12-15 16:58 UTC, bakulf commented on docs/mozillavpn_stage.json
> +    "ANDROID": "2.12.0",
Android is still 2.11 until the review is completed

2022-12-15 16:58 UTC, bakulf commented on docs/mozillavpn_stage.json
> +    "LINUX": "2.12.0",
is linux 2.12 released?

2022-12-15 16:58 UTC, bakulf commented on docs/mozillavpn_stage.json
> +      "platforms": ["ANDROID", "IOS", "LINUX", "MACOS", "WINDOWS"]
remove LINUX, ANDROID, IOS if they are not ready.

2022-12-15 17:02 UTC, bakulf requested changes

2022-12-15 17:02 UTC, bakulf commented on docs/mozillavpn_stage.json
> +      "date": "2022-12-06",
why this date?

2022-12-16 04:24 UTC, birdsarah requested changes
I don't understand this PR.

Please add some explanatory text or close it.

2022-12-16 04:24 UTC, birdsarah commented on docs/mozillavpn.json
> -    "MACOS": "2.12.0",
why is this PR attempting to revert the release of 2.12?

2022-12-20 13:14 UTC, mozrokafor commented
https://github.com/mozilla/mozillavpn-product-details/pull/53 migrating to

2022-12-20 13:14 UTC, closed without merging